version: '2'
services:
    webserver:
        image: nginx:latest
        container_name: ng01
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/src/app/
            - ./config:/etc/nginx/conf.d
        depends_on:
            - web
    web:
        build: .
        container_name: tula01
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        expose:
            - "8000"