# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('article', models.TextField(max_length=1024)),
                ('special_offer', models.TextField(default='', max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mainimg', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='MainImage')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=128)),
                ('anchor', models.CharField(max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, default='', max_length=32, null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=1024, null=True)),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tula.Holiday')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
